{
 "title": "Operatori Apeluri Intrare",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "company", "query": "luxdng" },
   {
    "name": "operatori",
    "query": "101,102,103,104,105,106,107,108,109,110"
   },
   {
    "name": "nume",
    "query": "101,102,103,104,105,106,107,108,109,110"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 2.4, "x": 0, "y": 0 },
   "repeat": "nume",
   "options": {
    "content": "<div align=\"center\" style=\"font-size:28px; text-align:center\">$nume</div>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Apeluri",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2.4, "x": 0, "y": 3 },
   "repeat": "operatori",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "calls{company=\"$company\",direction=\"inbound\",entity=\"by_operator\",extension=\"$operatori\",status=\"total\"}",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "calls",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "count" },
      { "condition": "AND", "key": "direction", "operator": "=", "value": "inbound" },
      { "condition": "AND", "key": "company", "operator": "=~", "value": "/^$company$/" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "total" },
      { "condition": "AND", "key": "extension", "operator": "=~", "value": "/^$operatori$/" }
     ]
    }
   ]
  },
  {
   "title": "Apeluri cu succes",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2.4, "x": 0, "y": 6 },
   "repeat": "operatori",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "calls{company=\"$company\",direction=\"inbound\",entity=\"by_operator\",extension=\"$operatori\",status=\"answered\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "calls",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "count" },
      { "condition": "AND", "key": "direction", "operator": "=", "value": "inbound" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "answered" },
      { "condition": "AND", "key": "extension", "operator": "=~", "value": "/^$operatori$/" },
      { "condition": "AND", "key": "company", "operator": "=~", "value": "/^$company$/" }
     ]
    }
   ]
  },
  {
   "title": "Minute vorbite",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2.4, "x": 0, "y": 10 },
   "repeat": "operatori",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "calls{company=\"$company\",direction=\"inbound\",entity=\"by_operator\",extension=\"$operatori\",type=\"duration\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "calls",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "/60" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "duration" },
      { "condition": "AND", "key": "direction", "operator": "=", "value": "inbound" },
      { "condition": "AND", "key": "extension", "operator": "=~", "value": "/^$operatori$/" },
      { "condition": "AND", "key": "company", "operator": "=~", "value": "/^$company$/" }
     ]
    }
   ]
  },
  {
   "title": "Medie apel",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2.4, "x": 0, "y": 14 },
   "repeat": "operatori",
   "fieldConfig": { "defaults": { "unit": "sec" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg_over_time(calls{company=\"$company\",direction=\"inbound\",extension=\"$operatori\",type=\"average_duration\"})",
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "calls",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "average_duration" },
      { "condition": "AND", "key": "company", "operator": "=~", "value": "/^$company$/" },
      { "condition": "AND", "key": "extension", "operator": "=~", "value": "/^$operatori$/" },
      { "condition": "AND", "key": "direction", "operator": "=", "value": "inbound" }
     ]
    }
   ]
  }
 ]
}